### ISSUE TITLE
imsrybr0 - Users can bypass sanctions check for redemption

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-midas-minter-redeemer-judging#85]
imsrybr0

High

# Users can bypass sanctions check for redemption

### Summary

`mTBIIL@_beforeTokenTransfer` is only checking if the sender and recipient are blacklisted, allowing sanctioned users to bypass the sanctions check for redemption by transferring `mTBILL`/`mBASIS` tokens to a non sanctioned address.

### Root Cause

[mTBILL.sol](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/mTBILL/mTBILL.sol#L82-L93)

```solidity
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual override(ERC20PausableUpgradeable) {
        if (to != address(0)) {
            _onlyNotBlacklisted(from);
            _onlyNotBlacklisted(to);
        }

        ERC20PausableUpgradeable._beforeTokenTransfer(from, to, amount);
    }
```

`mTBIIL@_beforeTokenTransfer` is not checking for sanctions.

### Internal pre-conditions

N/A

### External pre-conditions

User is not sanctioned initially.

### Attack Path

1. The user deposits to Midas by calling `depositInstant` and gets `mTBILL`/`mBASIS` tokens back.
2. The user is sanctioned.
3. The user can still redeem using `mTBILL`/`mBASIS` tokens by transferring them to a non sanctioned address.

### Impact

User bypasses the sanctions check for redemption.

### PoC

N/A

### Mitigation

Add sanctions check on the `mTBILL` transfers as well.

**Comment by imsrybr0** [comment]
Escalate

I'm not sure why this was excluded.

An explicit restriction on [instant redemption](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L134) can be bypassed.

A somewhat similar issue for [blacklist](https://github.com/sherlock-audit/2024-05-midas-judging/issues/9) was judged as a High in the previous contest.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I'm not sure why this was excluded.
> 
> An explicit restriction on [instant redemption](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L134) can be bypassed.
> 
> A somewhat similar issue for [blacklist](https://github.com/sherlock-audit/2024-05-midas-judging/issues/9) was judged as a High in the previous contest.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Why this has to check for sanctioned users? As I see in the code comments above the function, it explicitly says that this is the "function to ban blaclisted users from using the token functions". Hence, why it should check for sanctioned users and can't sanctioned users be blacklisted?

**Comment by imsrybr0** [comment]
Hi @WangSecurity, 

If it doesn't check for sanctions then the check in redemption just becomes useless.

As for the blacklist, yes, sanctionned users can be blacklisted but they can also bypass that just by renouncing the blacklist role. This is an issue from the previous audit which the team chose not to fix.

**Comment by 0xAadi** [comment]
> This is an issue from the previous audit which the team chose not to fix.

They are fixed the renouncing issue. Please see https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/52b77ba39be51f18a5b0736dfbe7f2acbbeba6e3/midas-contracts/contracts/access/MidasAccessControl.sol#L63C1-L65C6

**Comment by imsrybr0** [comment]
@0xAadi , thanks for correcting that, somehow I missed that completely, my bad 🙏

**Comment by 0xRandluck** [comment]
sanctioned users can be blacklisted

**Comment by imsrybr0** [comment]
Hi @0xRandluck, yes, as mentioned by 0xAadi.

The team is aware of this but still decided to add the sanction check to the instant redemption, which means they deemed the blacklist administrative reaction workaround as not sufficient otherwise they would have just used the blacklist check.

**Comment by WangSecurity** [comment]
After rechecking, I can confirm that the code comments are not outdated and this function is specifically to check the blacklisted address and it's the intention to not check for sanctioned users. Hence, this issue has to remain invalid. Planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Hi @WangSecurity , 

It is more likely that it was a mistake since the sanctions feature was only added after the blacklist feature (check the previous audit code base, the comment didn't change since then).

Similar to the blacklist check, it doesn't make sense to have the sanctions check in instant redemption only and not on the transfer too.

**Comment by WangSecurity** [comment]
I understand, thank you for raising this concern, but it wasn't a mistake, it's actually intended that only blacklisted addresses are checked and not sanctioned ones. The decision remains, planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
I'm not quite sure I fully understand the reasoning here, how can it be intentional to restrict access to a functionality and allow users to bypass that restriction at the same time?

**Comment by WangSecurity** [comment]
Excuse me for the confusion, I didn't mean to restrict and allow. In the mTBILL contract, this check before the transfer is intended to check only for blacklisted addresses, not for the sanctioned ones. Therefore, here the restriction is not bypassed, because the restriction for sanctioned users shouldn't be here. I see the scenario when the sanctioned user can transfer their tokens to a different address, but still, the check here is only for blacklisted users, unlike the checks inside the protocol contracts. If you need, here's the quote from the team:
> it is indented. We will just blacklist those users manually if necessary

The decision remains, reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Hi @WangSecurity,

Was this information available somewhere during the contest ? If not, this only confirms that the restriction can indeed be bypassed and that in that case the team would revert to the manual workaround of blacklisting.

**Comment by WangSecurity** [comment]
In the code comments above the `_beforeTokenTransfer` function it says the function checks for blacklisted tokens. Also, there is no information there should be a check for sanctioned users and the protocol isn't obligated to list all of their design decisions. Therefore, here the protocol works as intended, planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Hi @WangSecurity,

> In the code comments above the _beforeTokenTransfer function it says the function checks for blacklisted tokens. 

We have already discussed the code comment, it was there before the sanctions restriction was added.

> Also, there is no information there should be a check for sanctioned users 

The code rules here in the same way a lack of access control would or a missing accounting update would for example even if the function comment didn't mention they were needed.

> and the protocol isn't obligated to list all of their design decisions.

The comment you shared from the sponsor confirmed that the restriction can be bypassed and that in such a case they would manually workaround it.  
This implies that they have an off chain mechanism for tracking users that are sanctionned and bypass the restriction by transferring the mTBILL/mBASIS to non sanctionned addresses in order to blacklist them. 
There is no description of such an off chain mechanism in the README.

**Comment by WangSecurity** [comment]
> We have already discussed the code comment, it was there before the sanctions restriction was added.

The comments stand above the rules if they're up-to-date. The fact that these comments were the same before the sanctioned check was introduced doesn't make them outdated and I've confirmed they're **not** outdated.

> The code rules here in the same way a lack of access control would or a missing accounting update would for example even if the function comment didn't mention they were needed.

Fair enough, but in the case mentioned by you the access controls are missed and they should be there (i.e. it's not intended to not use them). Here it's intended to check for the blacklisted addresses.

> The comment you shared from the sponsor confirmed that the restriction can be bypassed and that in such a case they would manually workaround it.
This implies that they have an off chain mechanism for tracking users that are sanctionned and bypass the restriction by transferring the mTBILL/mBASIS to non sanctionned addresses in order to blacklist them.
There is no description of such an off chain mechanism in the README.

I didn't mention any off-chain mechanisms and I don't see how they're implied here. The quote I shared was to only show that the comments are correct and that the protocol doesn't intend to put any checks on sanctioned users for the mTbill transfer.

The decision remains, reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
> The comments stand above the rules if they're up-to-date. The fact that these comments were the same before the sanctioned check was introduced doesn't make them outdated and I've confirmed they're not outdated.

This was only confirmed post contest.

> Fair enough, but in the case mentioned by you the access controls are missed and they should be there (i.e. it's not intended to not use them). Here it's intended to check for the blacklisted addresses.

My main point is that you cannot always rely on the comments for intended design especially if the code doesn't make sense. If anything, from the code, the check should be on the transfer as it's the most restrictive.
And again, here, the intended design was only confirmed post contest.

> I didn't mention any off-chain mechanisms and I don't see how they're implied here. The quote I shared was to only show that the comments are correct and that the protocol doesn't intend to put any checks on sanctioned users for the mTbill transfer.

I don't see any other option, unless of course, manually monitoring transactions is considered a viable one.

**Comment by WangSecurity** [comment]
> This was only confirmed post contest.

The comments are **not** outdated and stand above the rules by default.

> My main point is that you cannot always rely on the comments for intended design especially if the code doesn't make sense. If anything, from the code, the check should be on the transfer as it's the most restrictive.
And again, here, the intended design was only confirmed post contest.

The reason why code comments stand above the judging rules is because they explain how the protocol should and intended to work and we can rely on them. Secondly, the code comments were available at the time of the contest and all the Watsons can ask the sponsors if the code comments are up-to-date and what the intended design is during the contest. Unfortunately, I don't have the ability to that during the contest. 

Hence, the code works as expected, thus, this is only the design recommendation, planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
> The comments are not outdated

This is based on post contest information.

That same information is an aknowledgment of the presence of an issue and that a workaround would be applied.

Neither the aknowledgment, nor the workaround were described in the README.

> and stand above the rules by default.

I'm not saying they don't.
I would understand your stance if this report was about removing the blacklist restriction from the transfer or if the sanction restriction was not used anywhere else where a transfer is also involved.

> The reason why code comments stand above the judging rules is because they explain how the protocol should and intended to work and we can rely on them.

This is simply not true in every single case as I explained earlier :
* A missing access control doesn't need to be mentioned as needed in the comments to be valid.
* A missing accounting update doesn't need to be mentioned in the comments to be valid.

> Secondly, the code comments were available at the time of the contest and all the Watsons can ask the sponsors if the code comments are up-to-date and what the intended design is during the contest.

The watsons have no obligation to ask the sponsor especially when the code itself is self explanatory and there is a clear discrepancy between the code as a hole and the comment.
Sponsors on the other hand, are required to list known issues and any relevant off chain mechanisms.

> Hence, the code works as expected, thus, this is only the design recommendation

This conclusion is again based on post contest information and to be honest, I don't quite understand it as from my perspective it essentially says : "It's working as expected because we **now** know that the team was **always** aware that this is indeed an issue but they **intended** to have it anyways and **always** had an off chain workaround for it, making this **now** a design recommendation, even if they didn't list the issue as a known issue or it's off chain workaround in the README **during the constest**, despite **always** knowing about both."

**Comment by WangSecurity** [comment]
> This is based on post contest information.
That same information is an aknowledgment of the presence of an issue and that a workaround would be applied.
Neither the aknowledgment, nor the workaround were described in the README.

As I've said above, code comments override the rules like the README. They do it by default and it's known that code comments stand above the rules during the contest and even before the contest. I'm sorry, but it's not a debatable question, it's how it works.

> This is simply not true in every single case as I explained earlier :
A missing access control doesn't need to be mentioned as needed in the comments to be valid.
A missing accounting update doesn't need to be mentioned in the comments to be valid.


Yes, but the word to highlight here is "missing", there is nothing missing in the `beforeTransfer` function and it works as expected.

> The watsons have no obligation to ask the sponsor especially when the code itself is self explanatory and there is a clear discrepancy between the code as a hole and the comment.
Sponsors on the other hand, are required to list known issues and any relevant off chain mechanisms.

There's no discrepancy between the code and the comment. The reason that in one part of the protocol there is a sanctioned users check, it doesn't mean it should be in another part of the code. Moreover, it's not an issue there no such check here, the issue would be if there should have been a check, but it was missed. Here it's not the case and there is no issue.

> This conclusion is again based on post contest information and to be honest, I don't quite understand it as from my perspective it essentially says

The decision is based on the code comment which stands above the rules and was available throughout the entire contest. Moreover, the statement you've put in quotes is not what I've said. I've never said the sponsor was always aware of this is indeed an issue, it's not an issue. I've never said they always had an off-chain mechanisms, you've said this, nobody else said there's an off-chain mechanism about it. It shouldn't have been listed in the README because it's not an issue and I or the sponsor don't say "there is an off-chain mechanisms to deal with it". 

The decision remains the same, reject the escalation and leave the report as it is. Excuse me, but the points I've said above are not a debatable question and we start to repeat the same points again, hence, if that continues, I will just reject the escalation, because we can't extend this one by repeating the same arguments. If you still don't understand, please contact me on discord and I'll explain.

**Comment by imsrybr0** [comment]
Please go ahead and reject the escalation, there is no point in further extending this discussion if the decision is non debatable.

EDIT : One last question : If the transfer didn't have a blacklist check and the comment didn't mention it but there was a blacklist check in the redemption, would that issue be valid or not ? If yes, would it still be valud if the sponsor said post contest that they know about it, intended to have it and will just burn blacklisted users tokens as a workaround?

**Comment by WangSecurity** [comment]
I’m not sure I understand your question, so please reach out to me on discord so we can discuss it.

The decision remains, reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Here is what I meant, in this situation :

```solidity
contract mTBILL is ERC20PausableUpgradeable, IMTbill {
    // ...
    function burn(address from, uint256 amount)
        external
        onlyRole(_burnerRole(), msg.sender)
    {
        _burn(from, amount);
    }

    function pause() external override onlyRole(_pauserRole(), msg.sender) {
        _pause();
    }

    // ...

    /**
     * @dev overrides _beforeTokenTransfer function
     */
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual override(ERC20PausableUpgradeable) {
        ERC20PausableUpgradeable._beforeTokenTransfer(from, to, amount);
    }

    // ...
}
```

```solidity
contract RedemptionVault is ManageableVault, IRedemptionVault {
    // ...
    function redeemInstant(
        address tokenOut,
        uint256 amountMTokenIn,
        uint256 minReceiveAmount
    )
        external
        virtual
        whenFnNotPaused(this.redeemInstant.selector)
        onlyGreenlisted(msg.sender)
        onlyNotBlacklisted(msg.sender)
    {
        address user = msg.sender;

        (
            uint256 feeAmount,
            uint256 amountMTokenWithoutFee
        ) = _calcAndValidateRedeem(user, tokenOut, amountMTokenIn, true, false);

        _requireAndUpdateLimit(amountMTokenIn);

        uint256 tokenDecimals = _tokenDecimals(tokenOut);

        uint256 amountMTokenInCopy = amountMTokenIn;
        address tokenOutCopy = tokenOut;
        uint256 minReceiveAmountCopy = minReceiveAmount;

        (uint256 amountMTokenInUsd, uint256 mTokenRate) = _convertMTokenToUsd(
            amountMTokenInCopy
        );
        (uint256 amountTokenOut, uint256 tokenOutRate) = _convertUsdToToken(
            amountMTokenInUsd,
            tokenOutCopy
        );

        uint256 amountTokenOutWithoutFee = _truncate(
            (amountMTokenWithoutFee * mTokenRate) / tokenOutRate,
            tokenDecimals
        );

        require(
            amountTokenOutWithoutFee >= minReceiveAmountCopy,
            "RV: minReceiveAmount > actual"
        );

        _requireAndUpdateAllowance(tokenOutCopy, amountTokenOut);

        mToken.burn(user, amountMTokenWithoutFee);
        if (feeAmount > 0)
            _tokenTransferFromUser(address(mToken), feeReceiver, feeAmount, 18);

        _tokenTransferToUser(
            tokenOutCopy,
            user,
            amountTokenOutWithoutFee,
            tokenDecimals
        );

        emit RedeemInstant(
            user,
            tokenOutCopy,
            amountMTokenInCopy,
            feeAmount,
            amountTokenOutWithoutFee
        );
    }

    // ...
}
```

* Would a report describing the ability to bypass the blacklist restriction in the redemption by transferring tokens be a valid a issue ?
* Would that depend on post contest information provided by the sponsor saying that they know about it and have a workaround for it where they will just pause and burn blacklisted users tokens ?

**Comment by WangSecurity** [comment]
Hm, it's a good question. Before I answer, I want to make sure that it doesn't affect the validity of this issue and my previous decision remains.

If the issue was like the one described above, I would indeed lean towards this being an issue. @imsrybr0 do you mind if I resolve the escalation now?

**Comment by imsrybr0** [comment]
For sure, my question was not meant to change the decision as it already appeared to be final. I'm just genuinely curious because from my point of view both situations are the same.

Please go ahead and reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imsrybr0](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/85/#issuecomment-2328249843): rejected
