### ISSUE TITLE
eeyore - Multiple instances of calculations with incorrect rounding directions that are unfavorable to the protocol.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#92]
eeyore

Medium

# Multiple instances of calculations with incorrect rounding directions that are unfavorable to the protocol.

## Summary

Within all the contracts, all calculations are rounded down, even when such rounding favors the user. This is incorrect, as all roundings in calculations should favor the protocol.

## Vulnerability Details

There are multiple instances of this issue:

1. Within the `_getFeeAmount()` function, the rounding should be up.

```solidity
File: ManageableVault.sol
540:         return (amount * feePercent) / ONE_HUNDRED_PERCENT; // <== should be rounding up
```

The fee calculations should always round the value up in favor of the protocol.

2. `feeTokenAmount` is truncated prematurely, leading to rounding in favor of the user.

```solidity
File: DepositVault.sol
379:         feeTokenAmount = _truncate( // <== truncated prematurely as feeTokenAmount is used as a multiplier for feeInUsd calculation
380:             _getFeeAmount(userCopy, tokenIn, amountToken, isInstant, 0),
381:             tokenDecimals
382:         );
383:         amountTokenWithoutFee = amountToken - feeTokenAmount; // <== should _truncate() here only
384: 
385:         uint256 feeInUsd = (feeTokenAmount * tokenInRate) / 10**18; // <== feeTokenAmount used as a multiplier in fee amount calculation
```

3. Rounding down in the `feeInUsd` calculation.

```solidity
File: DepositVault.sol
385:         uint256 feeInUsd = (feeTokenAmount * tokenInRate) / 10**18; // <== should be rounding up in favor of the protocol.
```

## Impact

Incorrect rounding will result in higher output amounts, favoring the user over the protocol.

## Code Snippet

https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/abstract/ManageableVault.sol#L540  
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L379-L385  

## Tools Used

Manual review.

## Recommendations

Round the value up instead of down in all mentioned instances.

**Comment by 0xklapouchy** [comment]
Escalate.

This is a valid issue.

The three showcased instances where rounding is done incorrectly occur within the same calculation for the `feeInUsd` value, and they compound on top of each other. The `feeInUsd` is later used to calculate the mint amount, potentially leading to an incorrect minting of up to 1 Finney of mTokens (0.0001 Ether of mTokens), which is not a dust amount.

The most important aspect is the premature truncation. While truncation is desired when calculating `amountTokenWithoutFee` to transfer more tokens from the user during deposit, it is not appropriate for all calculations where the fee is determined and subsequently deducted when calculating the mint amount.

Considering that WBTC can be used, truncation in this context can lead to a non-dust amount of fee being lost and not accounted for in the mint, resulting in more mTokens being minted to the user than should be.

Additionally, the duplicate issue #27 is invalid. It incorrectly suggests that the `_truncate()` function works incorrectly, which is not the case, and the example provided in that issue is incorrect.

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> This is a valid issue.
> 
> The three showcased instances where rounding is done incorrectly occur within the same calculation for the `feeInUsd` value, and they compound on top of each other. The `feeInUsd` is later used to calculate the mint amount, potentially leading to an incorrect minting of up to 1 Finney of mTokens (0.0001 Ether of mTokens), which is not a dust amount.
> 
> The most important aspect is the premature truncation. While truncation is desired when calculating `amountTokenWithoutFee` to transfer more tokens from the user during deposit, it is not appropriate for all calculations where the fee is determined and subsequently deducted when calculating the mint amount.
> 
> Considering that WBTC can be used, truncation in this context can lead to a non-dust amount of fee being lost and not accounted for in the mint, resulting in more mTokens being minted to the user than should be.
> 
> Additionally, the duplicate issue #27 is invalid. It incorrectly suggests that the `_truncate()` function works incorrectly, which is not the case, and the example provided in that issue is incorrect.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
@0xklapouchy could you make a POC showing the considerable loss? What would be the minimum and the maximum loss (in terms of %), or it's the same every time?

**Comment by 0xklapouchy** [comment]
@WangSecurity

The minimum loss is 0.
The maximum is 0.0001 USD worth of mTokens.

In max percentage terms, it depends on the deposited amount. It could be low `0.000001%` if 100 USD worth of tokens is deposited, or high `10%` if only 0.001 USD worth of tokens is deposited.

The issue highlights that the protocol did not account for rounding direction in any of its calculations. They are fortunate that the maximum discrepancy between what should be minted and what is actually minted is only 0.0001 USD worth of mTokens.

It can be acknowledged be the protocol and never fixed, but the issue is there and protocols should care about the rounding directions.

**Comment by WangSecurity** [comment]
Then, in that case I believe it has to be a low severity finding, since the max loss is 100x times smaller than 1 cent, i.e. it doesn't exceed small and finite amounts for medium severity:
> The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xklapouchy](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/92/#issuecomment-2328118550): rejected
